name: deploy
on:
  push:
    branches: ['BE','feature/ci-cd']
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make application.properties
        run: |
          pwd
          ls -al
          cd ./BE/src/main/resources
          touch ./application-secret.properties
          echo "${{ secrets.APPLICATION_SECRET }}" > ./application-secret.properties
        shell: bash

        ## gradle build
      - name: Build with Gradle
        run: |
          cd ./BE
          chmod +x gradlew
          ./gradlew clean build --exclude-task test
          cd ..
          cp ./BE/build/libs/BE-0.0.1-SNAPSHOT.jar i5niq.jar

      - name: Send jar to main server with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "i5niq.jar"
          target: "/home/ubuntu/"

      ## deploy to main
      - name: Deploy to main server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/
            pwd